# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QGIS_ISODATA
                                 A QGIS plugin
 An ISODATA plugin for QGIS.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-06-06
        copyright            : (C) 2018 by LaZzy
        email                : 924797163@qq.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load QGIS_ISODATA class from file QGIS_ISODATA.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .QGIS_ISODATA import QGIS_ISODATA
    return QGIS_ISODATA(iface)
